#!/usr/bin/env bash
# Extracts a GH_TOKEN for this container from your host's own `gh`
# session, mirroring opencode-model-eval's extract-opencode-key.sh
# pattern: runs entirely on the host, outside docker-compose, so the
# real token value never gets read into docker-compose.yml or any
# committed file -- only into a gitignored .env next to it.
#
# Usage:
#   bash tools/server/extract-github-token.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
readonly DEST="${SCRIPT_DIR}/.env"

if ! command -v gh >/dev/null 2>&1; then
    echo "gh is required on the host for this script (not found on PATH)." >&2
    exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "gh isn't authenticated on this host -- run 'gh auth login' first." >&2
    exit 1
fi

# `gh auth token` is gh's own documented command for exactly this --
# confirmed 2026-08-06 (cli/cli discussion #7435): it's the supported
# way to get the active token as plain text without touching
# hosts.yml directly.
token="$(gh auth token)"

{
    echo "# Generated by tools/server/extract-github-token.sh -- do not commit."
    echo "GH_TOKEN=${token}"
} > "${DEST}"
chmod 600 "${DEST}"

echo "Wrote GH_TOKEN to ${DEST} (from 'gh auth token' on this host)." >&2
echo "docker compose auto-loads .env from this directory -- no further wiring needed." >&2
